baseURL: "https://capybaratest.netlify.app/"
theme: "up-business-theme"
languageCode: "es"

title: "CAPYBARA"

# googleAnalytics: ""

summaryLength: 20

params:
  title: "CAPYBARA COOPERACIÓN"
  description: "Detectamos bullying en sus etapas iniciales, transformando la experiencia educativa de los niños para un futuro mejor"
  images: 
    - "images/logo_CAPYBARA-03.png"

  logo: "images/logo.png"

  favicons:
    themeColor: "#FFFFFF"
    backgroundColor: "#FFFFFF"
    faviconColor: "#000000"

  social:
    # dribbble: "#"
    # instagram: "#"
    # facebook: "#"
    # twitter: "#"

  location:
    - "Av. Las Condes 12461, Las Condes, Región Metropolitana, Chile 7590943"
    # - "4517 Washington Ave. Manchester, Kentucky 39495"

  contact:
    - "hola@capybara.cl"
    # - "207.555.0119"

  copyright: "© 2024 Capybara All Rights Reserved"

menus:
  main:
    - name: "Home"
      url: "/#hero"
      weight: 1

    # - name: "¿Cómo trabajamos?"
    #   url: "/#"
    #   weight: 2

    # - name: "Nuestro equipo"
    #   url: "/#"
    #   weight: 3

    # - name: "Precios"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

  buttons:
    - name: "Agenda una llamada"
      url: "mailto:hola@capybara.cl"
      weight: 5
      pre: "btn btn-primary text-light"

  footer:
    - name: "Home"
      url: "/#"
      weight: 1

    - name: "Hablemos!"
      url: "mailto:hola@capybara.cl"
      weight: 2
    # - name: "¿Cómo trabajamos?"
    #   url: "/#"
    #   weight: 2

    # - name: "Nuestro equipo"
    #   url: "/#"
    #   weight: 3

    # - name: "Precios"
    #   url: "/#"
    #   weight: 4

    # - name: "Blog"
    #   url: "/blog"
    #   weight: 5

taxonomies:
  series: "series"
  tags: "tags"
